sudo: required
language: bash
services:
  - docker
addons:
  apt:
    packages:
      - qemu-user-static
      - binfmt-support
env:
  global:
    - DOCKER_REPO: thebiggerguy/restful-sunsaver
  matrix:
    - ARCH=amd64   TYPE=docker
    - ARCH=arm32v7 TYPE=docker
script:
  - sed --in-place "s/FROM /FROM ${ARCH}\//g" Dockerfile
  - docker build --tag="thebiggerguy/restful-sunsaver:latest" .