language: rust
services:
  - docker
sudo: required

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache:
  - cargo
  - docker

install: true

stages:
  - name: test
  - name: lint
  - name: docker

# Default script is the "test" stage
script:
  - cargo build
  - cargo test

jobs:
  include:
    - stage: lint
      rust: stable
      install:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all-targets --all-features -- -D warnings -A clippy::needless-pass-by-value -A clippy::float_cmp

    - stage: docker
      rust: stable
      script:
        - |
          tag_name = "${TRAVIS_BRANCH}";
          if [ "${TRAVIS_BRANCH}" == "master" ]; then
            tag_name = "latest";
          fi
          .travis/build-docker-image.sh "thebiggerguy/restful-sunsaver:${tag_name}";
