language: rust
services:
  - docker
sudo: required

rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly

cache:
  - cargo
  - $HOME/.cargo
  - docker
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt-preview --toolchain ${TRAVIS_RUST_VERSION}
script:
  - if [ "${TRAVIS_RUST_VERSION}" == "nightly" ]; then
      cargo fmt --all -- --check
    else
      cargo fmt --all -- --write-mode=diff
    fi
  - cargo build
  - cargo test
after_success:
  - if [ "${TRAVIS_RUST_VERSION}" == "stable" ]; then
      if [ "${TRAVIS_BRANCH}" == "master" ]; then
        .travis/build-docker-image.sh "thebiggerguy/restful-sunsaver:latest"
      fi
      if [ "${TRAVIS_BRANCH}" == "dev" ]; then
        .travis/build-docker-image.sh "thebiggerguy/restful-sunsaver:dev"
      fi
    fi
