language: rust
services:
  - docker
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test
- (test "${TRAVIS_RUST_VERSION}" == "stable" || make docker-latest)